#!/bin/bash
# AI News Digest - GitHub Auto Deploy
# 使い方: ./deploy-to-github.sh [morning|noon|evening]

set -e

EDITION="${1:-default}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
REPO_DIR="$WORKSPACE_DIR/ai-news-digest"
OUTPUT_DIR="$WORKSPACE_DIR/news-output"
ENV_FILE="$WORKSPACE_DIR/.env"

echo "🚀 AI News Digest - GitHub Deploy"
echo "=================================="
echo ""

# Load .env if exists
if [ -f "$ENV_FILE" ]; then
  export $(grep -v '^#' "$ENV_FILE" | xargs)
else
  echo "⚠️  Warning: .env file not found at $ENV_FILE"
  echo "   Trying to use existing GITHUB_TOKEN environment variable..."
fi

if [ -z "$GITHUB_TOKEN" ]; then
  echo "❌ GITHUB_TOKEN not set"
  exit 1
fi
echo "✅ GITHUB_TOKEN loaded"
echo ""

DATE=$(date +%Y-%m-%d)

# edition に応じてファイル名を決定
if [ "$EDITION" = "morning" ] || [ "$EDITION" = "noon" ] || [ "$EDITION" = "evening" ]; then
  SRC_HTML="$OUTPUT_DIR/${DATE}-${EDITION}.html"
  SRC_JSON="$OUTPUT_DIR/${DATE}-${EDITION}.json"
  ARCHIVE_NAME="${DATE}-${EDITION}.html"
  EDITION_LABEL="$EDITION"
else
  SRC_HTML="$OUTPUT_DIR/${DATE}.html"
  SRC_JSON="$OUTPUT_DIR/${DATE}.json"
  ARCHIVE_NAME="${DATE}.html"
  EDITION_LABEL="default"
fi

if [ ! -f "$SRC_HTML" ]; then
  echo "❌ HTML file not found: $SRC_HTML"
  echo "   Run: ./run-digest.sh $EDITION"
  exit 1
fi

# index.html（最新版として上書き）
echo "📂 Copying files..."
cp "$SRC_HTML" "$REPO_DIR/docs/index.html"
cp "$SRC_HTML" "$REPO_DIR/archive/$ARCHIVE_NAME"
cp "$SRC_JSON" "$REPO_DIR/data/$(basename $SRC_JSON)"

echo "✅ Files copied:"
echo "   - docs/index.html（最新）"
echo "   - archive/$ARCHIVE_NAME"
echo "   - data/$(basename $SRC_JSON)"
echo ""

# Generate archive index
echo "📚 Generating archive index..."
node "$SCRIPT_DIR/generate-archive-index.js"
echo ""

# Git push
cd "$REPO_DIR"
git remote set-url origin "https://${GITHUB_TOKEN}@github.com/takasaka-ctrl/ai-news-digest.git"

if [ -z "$(git status --porcelain)" ]; then
  echo "ℹ️  No changes to commit"
  exit 0
fi

EDITION_EMOJI="📰"
[ "$EDITION" = "morning" ]  && EDITION_EMOJI="🌅"
[ "$EDITION" = "noon" ]     && EDITION_EMOJI="☀️"
[ "$EDITION" = "evening" ]  && EDITION_EMOJI="🌙"

git add .
git commit -m "$EDITION_EMOJI AI Chronicle update: ${DATE} (${EDITION_LABEL})

Auto-generated by Athena (OpenClaw)
Edition: $EDITION_LABEL
Archive: archive/$ARCHIVE_NAME"

git push origin main

echo ""
echo "✅ Deploy complete!"
echo "🌐 https://takasaka-ctrl.github.io/ai-news-digest/"
echo "📅 Archive: https://takasaka-ctrl.github.io/ai-news-digest/archive/$ARCHIVE_NAME"
echo "⏱️  GitHub Pagesのキャッシュ更新まで1-3分かかります"
