#!/bin/bash
# Compass Report Generator
# Called by cron job every morning at 7:00 JST

set -e

WORKSPACE="/home/node/.openclaw/workspace"
VAULT="/mnt/vault"
TODAY=$(date +%Y-%m-%d)
WEEK_AGO=$(date -d '7 days ago' +%Y-%m-%d)

echo "🧭 Generating Compass Report for $TODAY..."

# This script collects data; the actual report is generated by Athena via cron agentTurn
# The agent will:
# 1. Read channels/compass.md for instructions
# 2. Scan Vault for recent memos
# 3. Check pending-ideas.json for #lab status
# 4. Review memory/YYYY-MM-DD.md for #imagelab activity
# 5. Format and post to #compass

echo "✅ Compass report job triggered. Athena will handle the rest."
